var namespaceresdb__driver_1_1exceptions =
[
    [ "AmountError", "classresdb__driver_1_1exceptions_1_1AmountError.html", null ],
    [ "AssetIdMismatch", "classresdb__driver_1_1exceptions_1_1AssetIdMismatch.html", null ],
    [ "BadRequest", "classresdb__driver_1_1exceptions_1_1BadRequest.html", null ],
    [ "ConfigurationError", "classresdb__driver_1_1exceptions_1_1ConfigurationError.html", null ],
    [ "CyclicBlockchainError", "classresdb__driver_1_1exceptions_1_1CyclicBlockchainError.html", null ],
    [ "DatabaseAlreadyExists", "classresdb__driver_1_1exceptions_1_1DatabaseAlreadyExists.html", null ],
    [ "DatabaseDoesNotExist", "classresdb__driver_1_1exceptions_1_1DatabaseDoesNotExist.html", null ],
    [ "DoubleSpend", "classresdb__driver_1_1exceptions_1_1DoubleSpend.html", null ],
    [ "DuplicateTransaction", "classresdb__driver_1_1exceptions_1_1DuplicateTransaction.html", null ],
    [ "GatewayTimeout", "classresdb__driver_1_1exceptions_1_1GatewayTimeout.html", null ],
    [ "GenesisBlockAlreadyExistsError", "classresdb__driver_1_1exceptions_1_1GenesisBlockAlreadyExistsError.html", null ],
    [ "InputDoesNotExist", "classresdb__driver_1_1exceptions_1_1InputDoesNotExist.html", null ],
    [ "InvalidHash", "classresdb__driver_1_1exceptions_1_1InvalidHash.html", null ],
    [ "InvalidSignature", "classresdb__driver_1_1exceptions_1_1InvalidSignature.html", null ],
    [ "KeypairMismatchException", "classresdb__driver_1_1exceptions_1_1KeypairMismatchException.html", null ],
    [ "MissingPrivateKeyError", "classresdb__driver_1_1exceptions_1_1MissingPrivateKeyError.html", null ],
    [ "MultipleValidatorOperationError", "classresdb__driver_1_1exceptions_1_1MultipleValidatorOperationError.html", null ],
    [ "NotFoundError", "classresdb__driver_1_1exceptions_1_1NotFoundError.html", null ],
    [ "OperationError", "classresdb__driver_1_1exceptions_1_1OperationError.html", null ],
    [ "ResDBError", "classresdb__driver_1_1exceptions_1_1ResDBError.html", null ],
    [ "ResdbException", "classresdb__driver_1_1exceptions_1_1ResdbException.html", null ],
    [ "SchemaValidationError", "classresdb__driver_1_1exceptions_1_1SchemaValidationError.html", null ],
    [ "ServiceUnavailable", "classresdb__driver_1_1exceptions_1_1ServiceUnavailable.html", null ],
    [ "StartupError", "classresdb__driver_1_1exceptions_1_1StartupError.html", null ],
    [ "ThresholdTooDeep", "classresdb__driver_1_1exceptions_1_1ThresholdTooDeep.html", null ],
    [ "TimeoutError", "classresdb__driver_1_1exceptions_1_1TimeoutError.html", "classresdb__driver_1_1exceptions_1_1TimeoutError" ],
    [ "TransactionNotInValidBlock", "classresdb__driver_1_1exceptions_1_1TransactionNotInValidBlock.html", null ],
    [ "TransactionOwnerError", "classresdb__driver_1_1exceptions_1_1TransactionOwnerError.html", null ],
    [ "TransportError", "classresdb__driver_1_1exceptions_1_1TransportError.html", "classresdb__driver_1_1exceptions_1_1TransportError" ],
    [ "ValidationError", "classresdb__driver_1_1exceptions_1_1ValidationError.html", null ],
    [ "HTTP_EXCEPTIONS", "namespaceresdb__driver_1_1exceptions.html#a8a086bd49ea6ae81cafde8e5e467e0b2", null ]
];