var searchData=
[
  ['readme_0',['README',['../md__2github_2workspace_2service_2kv__service_2README.html',1,'']]],
  ['readme_2emd_1',['readme.md',['../README_8md.html',1,'(Global Namespace)'],['../service_2http__server_2README_8md.html',1,'(Global Namespace)'],['../service_2kv__service_2README_8md.html',1,'(Global Namespace)'],['../service_2pybind__sample_2README_8md.html',1,'(Global Namespace)'],['../service_2sdk__validator_2README_8md.html',1,'(Global Namespace)']]],
  ['register_5ftype_2',['register_type',['../classresdb__driver_1_1transaction_1_1Transaction.html#af67cd34f82736ec2e9c70d0977867621',1,'resdb_driver.transaction.Transaction.register_type()'],['../classresdb__validator_1_1transaction_1_1Transaction.html#af67cd34f82736ec2e9c70d0977867621',1,'resdb_validator.transaction.Transaction.register_type()']]],
  ['registering_20it_20under_20sajjad_20s_20ownership_3',['registering it under sajjad s ownership',['../md__2github_2workspace_2docs_2nft__market.html#autotoc_md7',1,'PART 1: Creating the Asset and registering it under Sajjad&apos;s ownership'],['../md__2github_2workspace_2service_2sdk__validator_2docs_2nft__market.html#autotoc_md48',1,'PART 1: Creating the Asset and registering it under Sajjad&apos;s ownership']]],
  ['remaining_20tasks_4',['remaining tasks',['../md__2github_2workspace_2docs_2research.html#autotoc_md16',1,'Remaining tasks'],['../md__2github_2workspace_2service_2sdk__validator_2docs_2research.html#autotoc_md57',1,'Remaining tasks']]],
  ['request_5',['request',['../classresdb__driver_1_1connection_1_1Connection.html#a19266ed871cd2ded25922bb8b06d730c',1,'resdb_driver::connection::Connection']]],
  ['requests_20asyncronous_6',['requests asyncronous',['../md__2github_2workspace_2service_2sdk__validator_2docs_2research.html#autotoc_md56',1,'Making client requests Asyncronous'],['../md__2github_2workspace_2docs_2research.html#autotoc_md15',1,'Making client requests Asyncronous']]],
  ['requirements_7',['requirements',['../md__2github_2workspace_2service_2pybind__sample_2README.html#autotoc_md39',1,'Requirements'],['../md__2github_2workspace_2service_2sdk__validator_2README.html#autotoc_md59',1,'Requirements']]],
  ['res_8',['res',['../namespacevalidator__example.html#ab0bd7560790c13b656fd58e17e35143e',1,'validator_example']]],
  ['resdb_9',['resdb',['../md__2github_2workspace_2docs_2nft__market.html',1,'Building a NFT market with resdb'],['../md__2github_2workspace_2service_2sdk__validator_2docs_2nft__market.html',1,'Building a NFT market with resdb'],['../classresdb__validator_1_1lib_1_1ResDB.html',1,'ResDB'],['../classresdb__driver_1_1driver_1_1Resdb.html',1,'Resdb'],['../namespaceresdb.html',1,'resdb']]],
  ['resdb_20validator_20code_20in_20python_10',['resdb validator code in python',['../md__2github_2workspace_2service_2sdk__validator_2README.html',1,'']]],
  ['resdb_5fdriver_11',['resdb_driver',['../namespaceresdb__driver.html',1,'']]],
  ['resdb_5fdriver_3a_3aconnection_12',['connection',['../namespaceresdb__driver_1_1connection.html',1,'resdb_driver']]],
  ['resdb_5fdriver_3a_3acrypto_13',['crypto',['../namespaceresdb__driver_1_1crypto.html',1,'resdb_driver']]],
  ['resdb_5fdriver_3a_3adriver_14',['driver',['../namespaceresdb__driver_1_1driver.html',1,'resdb_driver']]],
  ['resdb_5fdriver_3a_3adriver_5fexperiment_15',['driver_experiment',['../namespaceresdb__driver_1_1driver__experiment.html',1,'resdb_driver']]],
  ['resdb_5fdriver_3a_3aexceptions_16',['exceptions',['../namespaceresdb__driver_1_1exceptions.html',1,'resdb_driver']]],
  ['resdb_5fdriver_3a_3aoffchain_17',['offchain',['../namespaceresdb__driver_1_1offchain.html',1,'resdb_driver']]],
  ['resdb_5fdriver_3a_3apool_18',['pool',['../namespaceresdb__driver_1_1pool.html',1,'resdb_driver']]],
  ['resdb_5fdriver_3a_3atransaction_19',['transaction',['../namespaceresdb__driver_1_1transaction.html',1,'resdb_driver']]],
  ['resdb_5fdriver_3a_3atransport_20',['transport',['../namespaceresdb__driver_1_1transport.html',1,'resdb_driver']]],
  ['resdb_5fdriver_3a_3autils_21',['utils',['../namespaceresdb__driver_1_1utils.html',1,'resdb_driver']]],
  ['resdb_5fdriver_3a_3avalidate_22',['validate',['../namespaceresdb__driver_1_1validate.html',1,'resdb_driver']]],
  ['resdb_5fkv_5fclient_2ecpp_23',['resdb_kv_client.cpp',['../resdb__kv__client_8cpp.html',1,'']]],
  ['resdb_5fkv_5fclient_2eh_24',['resdb_kv_client.h',['../resdb__kv__client_8h.html',1,'']]],
  ['resdb_5fvalidator_25',['resdb_validator',['../namespaceresdb__validator.html',1,'']]],
  ['resdb_5fvalidator_3a_3acrypto_26',['crypto',['../namespaceresdb__validator_1_1crypto.html',1,'resdb_validator']]],
  ['resdb_5fvalidator_3a_3aexceptions_27',['exceptions',['../namespaceresdb__validator_1_1exceptions.html',1,'resdb_validator']]],
  ['resdb_5fvalidator_3a_3alib_28',['lib',['../namespaceresdb__validator_1_1lib.html',1,'resdb_validator']]],
  ['resdb_5fvalidator_3a_3amemoize_29',['memoize',['../namespaceresdb__validator_1_1memoize.html',1,'resdb_validator']]],
  ['resdb_5fvalidator_3a_3amodels_30',['models',['../namespaceresdb__validator_1_1models.html',1,'resdb_validator']]],
  ['resdb_5fvalidator_3a_3atransaction_31',['transaction',['../namespaceresdb__validator_1_1transaction.html',1,'resdb_validator']]],
  ['resdb_5fvalidator_3a_3autils_32',['utils',['../namespaceresdb__validator_1_1utils.html',1,'resdb_validator']]],
  ['resdberror_33',['resdberror',['../classresdb__validator_1_1exceptions_1_1ResDBError.html',1,'ResDBError'],['../classresdb__driver_1_1exceptions_1_1ResDBError.html',1,'ResDBError']]],
  ['resdbexception_34',['ResdbException',['../classresdb__driver_1_1exceptions_1_1ResdbException.html',1,'resdb_driver::exceptions']]],
  ['resdbkvclient_35',['resdbkvclient',['../classsdk_1_1ResDBKVClient.html#a07ed2589783d3fa90e1dc8dd1ead4121',1,'sdk::ResDBKVClient::ResDBKVClient()'],['../classsdk_1_1ResDBKVClient.html',1,'ResDBKVClient']]],
  ['research_2emd_36',['research.md',['../docs_2research_8md.html',1,'(Global Namespace)'],['../service_2sdk__validator_2docs_2research_8md.html',1,'(Global Namespace)']]],
  ['resilientdb_20sdk_37',['ResilientDB SDK',['../md__2github_2workspace_2README.html',1,'']]],
  ['resolve_5fclass_38',['resolve_class',['../classresdb__driver_1_1transaction_1_1Transaction.html#ae6c5425e15f6fa5a565ec73b411e4867',1,'resdb_driver.transaction.Transaction.resolve_class()'],['../classresdb__validator_1_1transaction_1_1Transaction.html#ae6c5425e15f6fa5a565ec73b411e4867',1,'resdb_validator.transaction.Transaction.resolve_class()']]],
  ['response_39',['response',['../namespaceendpoint__test.html#a8ab7bcb35ce5bba05608c72da6b4a0d3',1,'endpoint_test']]],
  ['ret_40',['ret',['../namespacevalidator.html#a46ac5459ea4e059d2e70cac8c64648ec',1,'validator']]],
  ['retrieve_41',['retrieve',['../classresdb__driver_1_1driver_1_1TransactionsEndpoint.html#a99346f6388758e4f467b72916931f558',1,'resdb_driver::driver::TransactionsEndpoint']]],
  ['root_20url_42',['root url',['../md__2github_2workspace_2docs_2nft__market.html#autotoc_md6',1,'Set up root url'],['../md__2github_2workspace_2service_2sdk__validator_2docs_2nft__market.html#autotoc_md47',1,'Set up root url']]],
  ['roundrobinpicker_43',['RoundRobinPicker',['../classresdb__driver_1_1pool_1_1RoundRobinPicker.html',1,'resdb_driver::pool']]],
  ['rule_44',['rule',['../md__2github_2workspace_2service_2sdk__validator_2README.html#autotoc_md64',1,'The Duplicate Transaction Rule'],['../md__2github_2workspace_2service_2sdk__validator_2README.html#autotoc_md66',1,'The input.fulfillment Rule'],['../md__2github_2workspace_2service_2sdk__validator_2README.html#autotoc_md63',1,'The output.amount Rule']]],
  ['rules_45',['The TRANSFER Transaction Rules',['../md__2github_2workspace_2service_2sdk__validator_2README.html#autotoc_md65',1,'']]],
  ['run_46',['run',['../classsdk_1_1CrowService.html#a13a43e6d814de94978c515cb084873b1',1,'sdk::CrowService']]],
  ['running_20crow_20service_20http_20endpoints_47',['Running Crow service (HTTP endpoints)',['../md__2github_2workspace_2README.html#autotoc_md21',1,'']]],
  ['running_20kv_20service_48',['Running KV service',['../md__2github_2workspace_2README.html#autotoc_md20',1,'']]],
  ['running_20the_20driver_49',['Running the driver',['../md__2github_2workspace_2README.html#autotoc_md23',1,'']]]
];
